### PR TITLE
Add TAMI

### PR DESCRIPTION
**Pull request by Astrrra**
Added the TAMI hackerspace from Tel Aviv

### CODE REVIEW

**Comment by rnestler** [comment]
Thanks a lot for the contribution! I visited TAMI last October. Say hi to Kfir :)

Regarding your endpoint: There seem to be issues with the JSON and the CORS headers according to the validator: https://validator.spaceapi.io/ui/?url=https://telavivmakers.space/nodered/spaceapi.json

**Comment by Astrrra** [comment]
Yeah, kfir told me about you when I was making the generator 😄

Will fix CORS soon, drafting the PR for now

**Comment by Astrrra** [comment]
Hm, I fixed the CORS headers, and the endpoint is returning valid JSON (tested with https://jsonlint.com), and, to the best of my knowledge, conforms to the schema. However, the validator still doesn't like something about the JSON, and I'm not sure what...

**Comment by rnestler** [comment]
> However, the validator still doesn't like something about the JSON, and I'm not sure what...

Yeah the error message is quite bad in this case.

It's the missing
```json
  "issue_report_channels": [
    "email"
  ],
```
part, which was required in the v0.13 schema.

**Comment by Astrrra** [comment]
Ah, got it! Validator's green now :)

**Review by rnestler — APPROVED** [review]
I currently get a timeout on https://telavivmakers.space/, but if the validator is otherwise green we can merge it anyways.

**Comment by Astrrra** [comment]
Yeah, the network is a bit unstable right now, should even out soon

**Pull request merged**
