### PR TITLE
Update Hackerspace KRK spaceapi URL

### PR DESCRIPTION
**Pull request by Teeed**

### CODE REVIEW

**Comment by dbrgn** [comment]
Thanks! The HTTPS version has a wrong certificate, do you plan to fix that or not? If yes, you could update the URL to HTTPS.

**Comment by Teeed** [comment]
Changed name from Hackerspace KRK to Hackerspace Krakow, https version should work now :)

**Comment by dbrgn** [comment]
Hm, I cannot reach https://spaceapi.hskrk.pl/ at all... Does it work for you?

```
danilo@c3po:~$ curl --max-time 10 https://spaceapi.hskrk.pl/
curl: (28) Connection timed out after 10000 milliseconds
```

**Comment by Teeed** [comment]
Hosting provider had some issues. It works now.

**Review by dbrgn — APPROVED** [review]
Great, thanks!

**Comment by rnestler** [comment]
@Teeed You may also consider to make your endpoint compatible with v14 of the API as well. Check the following links for more infos:
 * https://spaceapi.io/ 
 * https://spaceapi.io/docs/
 * https://validator.spaceapi.io/ui/

**Comment by dbrgn** [comment]
@rnestler don't forget about the migration guide 🙂 https://github.com/SpaceApi/schema/blob/master/MIGRATION.md

**Comment by Teeed** [comment]
Done, thank you! :)

**Comment by rnestler** [comment]
Also: Say hi to Wiktor 🙂

**Pull request merged**
