### PR TITLE
Add ChaosZone

### PR DESCRIPTION
**Pull request by dhavlik**
Representing people from different spaces across the east who are doing things together over the internet.

### CODE REVIEW

**Comment by gidsi** [comment]
Hey, are you trying to add something like a meta space for a group of spaces? It seems like the coordinates are in the middle of the ocean.

The file is also providing the icon attribute within the the state attribute but its just providing an empty string. Can you fix that?

**Comment by dhavlik** [comment]
> Hey, are you trying to add something like a meta space for a group of spaces? It seems like the coordinates are in the middle of the ocean.
Yes thats correct.

> The file is also providing the icon attribute within the the state attribute but its just providing an empty string. Can you fix that?
Fixed.

**Comment by gidsi** [comment]
> > Hey, are you trying to add something like a meta space for a group of spaces? It seems like the coordinates are in the middle of the ocean.
> 
> Yes thats correct.

Can you tell me what you're trying to achieve with it? I'm trying to understand your use-case better. 
Like what do you use the entry tor? 
Why is it in the middle of the ocean while it's a grouping of local spaces?

**Comment by dhavlik** [comment]
> > > Hey, are you trying to add something like a meta space for a group of spaces? It seems like the coordinates are in the middle of the ocean.
> > 
> > 
> > Yes thats correct.
> 
> Can you tell me what you're trying to achieve with it? I'm trying to understand your use-case better.
> Like what do you use the entry tor?

We are organising the virtual assembly "ChaosZone" at rc3. We will use the space status to have a signal for others if someone is "there". We also want to have a calendar for our events and meetings. 

> Why is it in the middle of the ocean while it's a grouping of local spaces?

During those pandemic times, geographic location does no longer matter. As our location is virtual, we can give everyone a chance to discover us by moving around.

**Comment by rnestler** [comment]
Well apart from the discussion how a virtual space should be handled this looks good to merge, right @gidsi? (CORS looks fine, https, content type, ...)

**Review by rnestler — APPROVED** [review]

**Comment by gidsi** [comment]
> Well apart from the discussion how a virtual space should be handled this looks good to merge, right @gidsi? (CORS looks fine, https, content type, ...)

Yeah, but not sure what to do with it in general. I mean the location has a purpose which is not there when the location is constantly moving.

A few things might break, but in general you're right.

**Comment by rnestler** [comment]
> Yeah, but not sure what to do with it in general. I mean the location has a purpose which is not there when the location is constantly moving.

Maybe we could add a special "cyber" (or maybe better "virtual" :wink:) location for that specific use-case of an online only space to meet. But that discussion belongs to the schema repository.

I'd propose to merge this, since @dhavlik has a use-case for it and continue the general discussion of "virtual" spaces in an issue in the schema repo.

**Pull request merged**
