### PR TITLE
Add Chaostreff Backnang to dictionary

### PR DESCRIPTION
**Pull request by psxde**

### CODE REVIEW

**Comment by gidsi** [comment]
Hey, 
your endpoint is compatible against v13, current version is v14, could you migrate? [Here](https://github.com/SpaceApi/schema/blob/master/MIGRATION.md#migration-from-013-to-14) is an HowTo.

You can check the status of your endpoint [here](https://validator.spaceapi.io/ui/?url=https://hacknang.de/spaceapi.json)

**Comment by rnestler** [comment]
> your endpoint is compatible against v13, current version is v14, could you migrate? [Here](https://github.com/SpaceApi/schema/blob/master/MIGRATION.md#migration-from-013-to-14) is an HowTo.

I just noticed that we should update the migration guide since we allowed `null` again to make it less painful to be compatible with both: https://github.com/SpaceApi/schema/pull/91

**Comment by psxde** [comment]
Hi,

we have updated our SpaceApi to v14.

**Comment by gidsi** [comment]
Looks good

**Review by gidsi — APPROVED** [review]

**Pull request merged**
