### PR TITLE
Add Hackerspace.Gent

### PR DESCRIPTION
**Pull request by qwaxys**

### CODE REVIEW

**Comment by gidsi** [comment]
Looks even better now :)

If you want to we could help you adding CORS headers, i've looked around and found this [repo](https://github.com/0x20/SpaceAPI-HSG) you might use. Unfortunately i can't see any config of the server, but server sends an ubuntu apache header so [this](https://enable-cors.org/server_apache.html) might help. 
If not we could merge it like it is :)

**Comment by qwaxys** [comment]
I've trued both with php and with .htaccess but we can't seem to change any headers at all.
We'll have a look into fixing this later but for now we'll keep it like it is :)

**Comment by dbrgn** [comment]
> If not we could merge it like it is :)

Hm, unfortunately it means that no web based application will be able to access the endpoint though...

@qwaxys does this line in `.htaccess` not work?

    Header set Access-Control-Allow-Origin "*"

See https://enable-cors.org/server_apache.html

**Comment by qwaxys** [comment]
It litterly doesn't. We've spend some timing scratching our head and
debugging, checking if mod_headers was loaded (it is now) but whatever we
pull, our headers don't seem to change.

Op wo 20 nov. 2019 om 09:26 schreef Danilo Bargen <notifications@github.com

**Comment by qwaxys** [comment]
I'll nudge the right people in the space to have a look at the CORS issue.
Can you merge for now?

**Comment by dbrgn** [comment]
Ah, sorry, forgot to press the merge button :smile:

**Comment by dbrgn** [comment]
Done :slightly_smiling_face: Thanks for adding your space!

**Pull request merged**
