### PR TITLE
Add Kreitek to directory.json 

### PR DESCRIPTION
**Pull request by danidask**
Added Kreitek

### CODE REVIEW

**Comment by amd77** [comment]
All URL's were corrected.

**Comment by rnestler** [comment]
> All URL's were corrected.

I'm still seeing the same URLs on https://metaespacio.kreitek.org/rest/spaceapi/ and they are still broken:
kreitek
kreitek-open
kreitek-closed

**Comment by amd77** [comment]
Sorry for the mistake. Retry now.

**Comment by rnestler** [comment]
> Sorry for the mistake. Retry now.

No problem :slightly_smiling_face: now it works.

**Pull request merged**
