### PR TITLE
Changed SpaceAPI URL for Ko-Lab in Mechelen, Belgium

### PR DESCRIPTION
**Pull request by SvenJanssens**

### CODE REVIEW

**Comment by s3lph** [comment]
Hi @SvenJanssens, thanks for the update. A few points:

- It seems that CORS is not enabled on your endpoint, meaning that it can't be queried by JavaScript browser apps. Usually just adding an `Access-Control-Allow-Origin: *` header to the webserver should be sufficient. Would it be possible to set up CORS on your end? I saw that your new endpoint is served through Cloudflare, according to their [docs](https://developers.cloudflare.com/cache/about/cors/) they simply pass this header "from the origin server to the browser".
- Your endpoint implements SpaceAPI v13, the current version is v14. Could you update your endpoint to support v14? [Here](https://github.com/SpaceApi/schema/blob/master/MIGRATION.md#migration-from-013-to-14) is an HowTo. It's usually trivial to support both versions simultaneously.
- It appears the latitude/longitude components of your geocoordinates are swapped.

You can use our validator to check for such issues yourself: https://validator.spaceapi.io/ui/?url=https://status.ko-lab.space/

**Comment by rnestler** [comment]
@SvenJanssens what's the status here?

**Review by rnestler — APPROVED** [review]

**Comment by rnestler** [comment]
> Your endpoint implements SpaceAPI v13, the current version is v14. Could you update your endpoint to support v14? [Here](https://github.com/SpaceApi/schema/blob/master/MIGRATION.md#migration-from-013-to-14) is an HowTo. It's usually trivial to support both versions simultaneously.

It seems to be v14 now: https://validator.spaceapi.io/ui/?url=https://status.ko-lab.space/

**Comment by dbrgn** [comment]
@SvenJanssens Do you plan to add the CORS headers to your endpoint? We could merge your entry it as-is, but it would be unreachable from all web-based API consumers.

**Comment by rnestler** [comment]
@SvenJanssens Ping.

I think we should merge this for now, since the old endpoint isn't available and the new one works apart from the wrong CORS headers.

**Comment by arnocornette** [comment]
Hi, 
I'm from Ko-Lab as well. I'll setup CORS now. Sorry for the delay.

**Comment by arnocornette** [comment]
@s3lph @rnestler  should be fixed. Please verify

**Comment by rnestler** [comment]
> should be fixed. Please verify

@arnocornette Yes looks fine now on on https://validator.spaceapi.io/ui/?url=https://status.ko-lab.space/. Thanks a lot :slightly_smiling_face:

**Pull request merged**
