### PR TITLE
Add NYC Resistor

### PR DESCRIPTION
**Pull request by georgyo**

### CODE REVIEW

**Comment by s3lph** [comment]
Hi @georgyo

Looks mostly good, but you may want to make sure your endpoint is fully v0.13 compliant. Currently the `issue_report_channels` field is missing. Even though abolished in v14, since your endpoint claims 0.13-support, you may still want to keep this field around.

You can use e.g. https://spaceapi.io/validator/ to check your endpoint for schema compliance.

**Comment by gidsi** [comment]
> Hi @georgyo
> 
> Looks mostly good, but you may want to make sure your endpoint is fully v0.13 compliant. Currently the `issue_report_channels` field is missing. Even though abolished in v14, since your endpoint claims 0.13-support, you may still want to keep this field around.
> 
> You can use e.g. https://spaceapi.io/validator/ to check your endpoint for schema compliance.

It gets reported as valid for some reason, must be a bug in the validator. I'm on it.

@georgyo lon and lat seems to be switched, beside that great work, happy to have you! :)

**Comment by georgyo** [comment]
Removed api 0.13 support and corrected the lat/lon.

**Review by gidsi — APPROVED** [review]
LGTM

**Pull request merged**
