### PR TITLE
remove old spaceapi, add new spaceapi for DIYWW

### PR DESCRIPTION
**Pull request by mm-chen**

### CODE REVIEW

**Comment by rnestler** [comment]
> The state icon links return 404 (http://status.diyww.de/open.png and http://status.diyww.de/close.png)

@gidsi Could we add this to the validator?

**Comment by mm-chen** [comment]
fixed

**Comment by gidsi** [comment]
> > The state icon links return 404 (http://status.diyww.de/open.png and http://status.diyww.de/close.png)
> 
> @gidsi Could we add this to the validator?

@rnestler Yeah, but i want to have [this](https://github.com/SpaceApi/validator/pull/38) merged before i add more features to the validator :)

**Comment by gidsi** [comment]
> fixed

looks good :)

**Pull request merged**
