### PR TITLE
Add second location for hackerspace drenthe

### PR DESCRIPTION
**Pull request by psy0rz**
We have a second location. Its the same organisation and members, but a separate  location/spacestate/etc

### CODE REVIEW

**Comment by rnestler** [comment]
Also consider adding support for v14. See https://spaceapi.io/ for an example which is both v0.13 and v14 compatible.

**Comment by psy0rz** [comment]
i tried this, but now the validator gives a blank page when i check our url. (this one is still fine: https://validator.spaceapi.io/ui/?url=https://mqtt.hackerspace-drenthe.nl/spaceapi)

**Comment by psy0rz** [comment]
aha: Validate failed: error: json: cannot unmarshal string into Go struct field spaceAPIVersion.api_compatibility of type []string

**Comment by psy0rz** [comment]
ok i fixed it. it turns out the validator doesnt like it when its a string instead of an array. it also doesnt like ["0.14"] instead of ["14"].

The validator server returns a 500 but this is not properly handled in the javascript browser part. Maybe so

**Comment by rnestler** [comment]
@psy0rz Yeah sorry the validator is a bit rough when errors happen :slightly_frowning_face: see also https://github.com/SpaceApi/validator/issues/64.

**Review by rnestler — APPROVED** [review]
Data looks good now, thanks :slightly_smiling_face:

**Pull request merged**
