### PR TITLE
Add Make Monmouth to the Space Directory

### PR DESCRIPTION
**Pull request by proffalken**

### CODE REVIEW

**Review by rnestler — CHANGES_REQUESTED** [review]
Your endpoint seems to return invalid data: https://validator.spaceapi.io/ui/?url=https://members.makemonmouth.co.uk/api/spacedirectory/

 * The `cam` array must have at minimum on entry. Just leave it out and it should be fine.
 * `lat` and `lon` are both `0`. Don't you have a physical location?

**Comment by proffalken** [comment]
@rnestler thanks for that, I didn't know that the validator existed.

The data is coming from https://github.com/membermatters/MemberMatters/ and at the moment and we don't have any cameras in the space so I'll put a dummy value in for that.

There's also [an issue with the way that MemberMatters stores the lat/long](https://github.com/membermatters/MemberMatters/issues/217) so we can only set our lat/long as `51, -2`, but hopefully that will be merged shortly.

I'll come back to this PR once I've got a valid JSON document! :)

**Comment by proffalken** [comment]
@rnestler JSON now validates with data that is close, but not 100% accurate... :rofl: 

I'll work on getting the PR's merged to allow for removing the cam URI's etc, but for now this should be good to go I think?

**Comment by rnestler** [comment]
> I'll work on getting the PR's merged to allow for removing the cam URI's etc, but for now this should be good to go I think?

I guess we can merge it as is and you can debug your issues / get your stuff merged :slightly_smiling_face:

**Comment by proffalken** [comment]
Thank you!

**Pull request merged**
