### PR TITLE
Update directectory.json

### PR DESCRIPTION
**Pull request by ReinVelt**
Added hackerspace Drenthe

### CODE REVIEW

**Comment by ReinVelt** [comment]
The CORS header is implemented now. 
Update to the V14 api is in the planning for end of this year

**Comment by dbrgn** [comment]
Thanks for the update! One more thing: The URLs seem to be invalid, all forward slashes are escaped but shouldn't be.

Additionally, somehow our validator cannot deal with your endpoint data, but doesn't give any useful error message 😕

```
danilo@bb8:~$ http GET https://hackerspace-drenthe.nl/spaceapi/spaceapi.php | http POST https://validator.spaceapi.io/v1/validate/
HTTP/1.1 200 OK
Content-Length: 82
Content-Type: application/json
Date: Wed, 20 Oct 2021 21:32:28 GMT
Vary: Origin

{
    "message": "(root): Invalid type. Expected: object, given: null\n",
    "valid": false
}
```

@gidsi do you know how to interpret that error message?

**Comment by ReinVelt** [comment]
I fixed the URLs and trying to find out the cause of the validation error

**Comment by dbrgn** [comment]
@ReinVelt Ah, I did not use the API properly! This way I get a result:

    http post https://validator.spaceapi.io/v2/validateURL url=https://hackerspace-drenthe.nl/spaceapi/spaceapi.php

The problem is that the `issue_report_channels` field is missing! Could you add that?

**Pull request closed without merging**
