### PR TITLE
Add Milton Keynes Makerspace

### PR DESCRIPTION
**Pull request by deanusjack**
Addition of static MK Makerspace endpoint.

Will change in future as the api gets live data, but would like to have the static file until that point hosted from github here.

Thanks

### CODE REVIEW

**Review by dbrgn — CHANGES_REQUESTED** [review]
Hi! The directory JSON is invalid (comma missing on preceding line, you should add your space in alphabetic order though) and the space JSON itself is invalid too (trailing commas). Could you fix that?

(We usually have a bot that validates the new entry, but it doesn't seem to run right now...)

**Comment by deanusjack** [comment]
Hi!
Thanks for getting back to me, I believe I have fixed all issues now. I have hopefully validated the schema correctly using another validator.

Please let me know if you see any further issues,
Thanks,
Jack

**Comment by rnestler** [comment]
There are still a few minor issues, but these aren't blockers for adding the space to the directory:
 * There are no CORS and Content-type headers. This is not possible as far as I know when hosting the JSON on GitHub. (See also https://spaceapi.io/provide-an-endpoint/)
 * state.open isn't allowed to be `null` in v14. But I think this is a real annoyance when trying to be v0.13 and v14 compatible and I'm thinking we should change v14 to allow `null` for `state.open` but deprecate it. (See also https://spaceapi.io/validator/)

**Review by rnestler — APPROVED** [review]

**Comment by dbrgn** [comment]
> There are no CORS and Content-type headers. This is not possible to fix as far as I know when hosting the JSON on GitHub.

I think you're wrong about that one, a `Access-Control-Allow-Origin: *` header is present in the response 🙂

**Comment by rnestler** [comment]
> I think you're wrong about that one, a Access-Control-Allow-Origin: * header is present in the response slightly_smiling_face

Huh. I swear I couldn't see it when I tested minutes ago, but now it is present. And also works when I enter the URL in the validator, so...

**Review by dbrgn — APPROVED** [review]

**Comment by dbrgn** [comment]
@deanusjack by the way, here you can find an alternative validator that will be integrated into the website at some point in time: https://validator.spaceapi.io/ui/

**Comment by deanusjack** [comment]
Cool, Thanks!

**Pull request merged**
