### PR TITLE
Added "Segmentation Vault"

### PR DESCRIPTION
**Pull request by creolis**

### CODE REVIEW

**Comment by dbrgn** [comment]
Thanks! Two issues:

- The endpoint is also reachable by HTTPS. Maybe you want to change the URL to use that by default?
- it seems that CORS is not enabled on your server, meaning that JavaScript applications cannot query your endpoint. Usually just adding a `access-control-allow-origin: *` header to the webserver should be sufficient.

Could you check? You can validate the endpoint with https://spaceapi.io/pages/validator.html. Would it be possible to set up CORS?

**Comment by creolis** [comment]
Hey! CORS is available using HTTPS, ... it seems that it's not delivered over HTTP. I'll redo URL, as the validator also seems to be fine with it.

**Comment by creolis** [comment]
this certainly feels like commit stealing ;)

**Comment by dbrgn** [comment]
Great, thanks! :slightly_smiling_face:

**Pull request merged**
