### PR TITLE
Add Pawprint Prototyping

### PR DESCRIPTION
**Pull request by rechner**
Adds [pawprintprototyping.org](https://pawprintprototyping.org/) - we are a small space in Santa Clara, California.

Furnished via the current version of the [MemberMatters SpaceDirectory integration](https://github.com/PawprintPrototyping/MemberMatters/blob/main/docs/SPACEDIRECTORY.md).

I've tried using the schema validator but see a 500 response from the validation backend when I try to submit, so not sure what's going on with that.  The output looks correct by my eye.

### CODE REVIEW

**Comment by dbrgn** [comment]
@gidsi seems like the validator has troubles processing this URL... Maybe the `Accept: application/json` header is not being sent?

**Comment by dbrgn** [comment]
Ahh, no, it's not about the content type!

@rechner you're including the API compatibility "0.14" in your response, but it should be "14"! (After 0.13 we switched to integer based versioning.) It seems that that trips up our validator.

Could you fix that in your endpoint?

**Comment by rechner** [comment]
Aaah ok.  I've opened [a PR with the upstream maintainers](https://github.com/membermatters/MemberMatters/pull/243), there's a couple of MemberMatters instances in the directory this would also effect.

**Comment by jabelone** [comment]
Hey @rechner thanks for the fix. I've merged it and created a release with this fix included (`v3.6.2`).

However, I've looked into it further and it looks like when the PR to add support for dynamic space api sensors was merged in I didn't check that it had been implemented as per the schema (I took the contributors word that it was compatible). This means the MemberMatters space api endpoint is currently returning objects instead of an array of objects in the `total_member_count` and `people_now_present` sensors. I'll fix that up later tonight and do another release - once that is fixed our space api implementation should correctly meet the space api schema.

Additionally, I've opened [an issue](https://github.com/SpaceApi/validator/issues/64) in the validator repo as it's very confusing when trying to test an endpoint and that endpoint provides data that can't be parsed as the validator shows no feedback in the UI.

**Comment by dbrgn** [comment]
@jabelone thanks for opening the validator issue! I agree that an error should be shown. (The root issue is probably that the validator doesn't know which schema to load becaues it doesn't know "0.14", and doesn't show a clean error message.)

Regarding MemberMatters, if it supports SpaceAPI, it would be nice if it could get listed at https://spaceapi.io/provide-an-endpoint/ ! You can find instructions on how to do that in the README at https://github.com/SpaceApi/website

**Comment by rnestler** [comment]
@rechner @jabelone any update on this?

**Comment by jabelone** [comment]
@rechner @rnestler `membermatters/membermatters:v3.6.3` is now available on docker hub. Let me know how it goes! Our instance passes the space api validator so hopefully this is resolved now. Sorry for the hassle! :)

**Comment by jabelone** [comment]
@dbrgn I've also added a PR [here](https://github.com/SpaceApi/website/pull/132) to add Member Matters to the website.

**Comment by rnestler** [comment]
@rechner The validator still returns an error: https://validator.spaceapi.io/ui/?url=https://members.pawprintprototyping.org/api/spacedirectory/

**Comment by rechner** [comment]
hi @rnestler - sorry about the long TTL, I've got our version updated and the validator is passing now.  I appreciate the patience!

**Review by s3lph — APPROVED** [review]
LGTM 🚀

**Pull request merged**
