### PR TITLE
Added CCC Frankfurt (CCC-FFM)

### PR DESCRIPTION
**Pull request by MyIgel**

### CODE REVIEW

**Comment by rnestler** [comment]
Oh one thing: You may want to change the `    "ccc_ext": "erfa",` bit to use `ext_ccc` which is the correct key.

**Comment by rnestler** [comment]
Also the state icons https://status.ccc-ffm.de/static/img/open and https://status.ccc-ffm.de/static/img/closed give a 404 error.

**Comment by MyIgel** [comment]
The 404 are a known issue, @telegnom will fix that soon (same for the ext_ccc ;) )

**Comment by telegnom** [comment]
Both issues should be fixed.

**Pull request merged**
