### PR TITLE
Updated all URLs to their https variant IF applicable

### PR DESCRIPTION
**Pull request by qwaxys**
Updated all URLs to their https variant IF applicable: all URLs have been manually tested.

### CODE REVIEW

**Comment by gidsi** [comment]
Thanks you! Help is really appreciated!

Unfortunately I don't feel well with changing the entries to HTTPS without talking to the affected spaces, so far it could be just an accident that HTTPS is available and if they're not taking care of it it might brake in the near future. But maybe @rnestler or @dbrgn have a different opinion :)

All in all we, currently, don't have a good plan  what to do with spaces that have a problem, trying to contact them kinda works but we still have around 40 spaces with different problems (that just spaces with broken endpoints, not including missing CORS header/no TLS/missing Content Header etc.).
Maybe you have a good idea on that topic :)

**Comment by qwaxys** [comment]
I suggest updating it because there is already a script checking if the API is online.

All of the tested ones had their website running on the same URL. I left out the ones with different IPs for API and website.

**Comment by gidsi** [comment]
> I suggest updating it because there is already a script checking if the API is online.
> 
> All of the tested ones had their website running on the same URL. I left out the ones with different IPs for API and website.

I would be fine with updating the URLs that return a 301 or 308 :)

**Comment by rnestler** [comment]
> I would be fine with updating the URLs that return a 301 or 308 :)

I'm definitely in favour of that as well :)

> Unfortunately I don't feel well with changing the entries to HTTPS without talking to the affected spaces, so far it could be just an accident that HTTPS is available and if they're not taking care of it it might brake in the near future. But maybe @rnestler or @dbrgn have a different opinion :)

Hmm I have mixed feelings about that. On one hand I agree with you that we shouldn't do the change "behind the back" of spaces. On the other hand "encrypt everything!" and if it is available anyways...

**Comment by dbrgn** [comment]
> Unfortunately I don't feel well with changing the entries to HTTPS without talking to the affected spaces, so far it could be just an accident that HTTPS is available and if they're not taking care of it it might brake in the near future. But maybe @rnestler or @dbrgn have a different opinion :)

I agree with this. We should encourage HTTPS URLs, but we should probably contact spaces about a suggested change before changing URLs. Ultimately the directory is a place where spaces enter their URLs, we just distribute those URLs as chosen by the spaces.

> All in all we, currently, don't have a good plan what to do with spaces that have a problem, trying to contact them kinda works but we still have around 40 spaces with different problems (that just spaces with broken endpoints, not including missing CORS header/no TLS/missing Content Header etc.).

Maybe some kind of linting tool ("we have detected potential problems with your SpaceAPI entry") could handle this. However, someone would need to write that first.

**Comment by gidsi** [comment]
> > All in all we, currently, don't have a good plan what to do with spaces that have a problem, trying to contact them kinda works but we still have around 40 spaces with different problems (that just spaces with broken endpoints, not including missing CORS header/no TLS/missing Content Header etc.).
> 
> Maybe some kind of linting tool ("we have detected potential problems with your SpaceAPI entry") could handle this. However, someone would need to write that first.

The validator is doing a quite a nice job on that right now, i'm working on a [frontend](https://shielded-peak-62758.herokuapp.com/) for it so the issues can be addressed with a possible solution. 
For me the issue lays more in communicating that to the spaces that do have the problem.

**Comment by rnestler** [comment]
@qwaxys Did you do this with some kind of script? If yes we could eventually adopt the script to only switch endpoints which redirect to https.

**Comment by qwaxys** [comment]
> @qwaxys Did you do this with some kind of script? If yes we could eventually adopt the script to only switch endpoints which redirect to https.

Manually, but if we can move some things to https, I'll gladly write a script to find all redirects?

**Comment by rnestler** [comment]
> Manually, but if we can move some things to https, I'll gladly write a script to find all redirects?

@gidsi @dbrgn What do you think? I'd be in favor in listing spaces which redirect to https as https directly.

**Comment by dbrgn** [comment]
I'm indifferent :man_shrugging: In case you do write a script for this, you'd have to be careful not to update URLs that use invalid / self-signed / expired certificates. There might be some that did not consciously enable HTTPS. (Although it should be standard nowadays...)

**Comment by qwaxys** [comment]
I can do it manually, I've got time :p
99% are letsencrypt anyway btw

**Comment by rnestler** [comment]
Is this still a thing? @qwaxys ?

**Comment by qwaxys** [comment]
I can do it manually in a few weeks, I'll add in my calendar for last week of september?

**Comment by rnestler** [comment]
> I can do it manually in a few weeks, I'll add in my calendar for last week of september?

Well no hurry, whatever fits your time and schedule :slightly_smiling_face: 

I assume you'll go with the script approach to change endpoints which redirect from http to https and have valid certificates and everything?

**Comment by qwaxys** [comment]
I'll just do a few a day and do it manually, it's not an endless list.

**Comment by zeno4ever** [comment]
I already have some php scripts running that get status from all hackerspaces via the api. I could add some checks (including http/https, CORS and lon/lat swapping, other checks) and email a space once per month with friendly question if they want to fix it.

**Comment by qwaxys** [comment]
That would certainly be helpful!

**Comment by gidsi** [comment]
> I already have some php scripts running that get status from all hackerspaces via the api. I could add some checks (including http/https, CORS and lon/lat swapping, other checks) and email a space once per month with friendly question if they want to fix it. 
> 

We have the metrics for that btw:
https://metrics.spaceapi.community/d/vHAszh5mz/spaceapi-directory?orgId=1

https://metrics.spaceapi.community/d/36qA_BCZk/space-details?orgId=1&var-Route=https:%2F%2Fspaceapi.tkkrlab.nl%2F

Lon/Lat switch is not automated, but it's part of the validator.

So far we send friendly reminders by hand, but it isn't working very well. 

I think the next step would be something like e.g. making the list public and use peer pressure to get things fixed or remove spaces automatically the moment they have a problem we can't fix.

**Comment by zeno4ever** [comment]
Ok, took some time but I have a php script that check most common errors. A first run wil send 69 emails with friendly request to fix the found errors. 39 entry's do not have a valid email to warn them, so these still have to be approached in a other way.  Remaining 79 entry's are ok.

I will run script firs manually, maybe later e.g. every other month (depending on the reactions)

Script can be found on https://github.com/zeno4ever/map-all-spaces/blob/master/private/validatespaceapi.php

**Comment by gidsi** [comment]
> Ok, took some time but I have a php script that check most common errors. A first run wil send 69 emails with friendly request to fix the found errors. 39 entry's do not have a valid email to warn them, so these still have to be approached in a other way. Remaining 79 entry's are ok.
> 
> I will run script firs manually, maybe later e.g. every other month (depending on the reactions)
> 
> Script can be found on https://github.com/zeno4ever/map-all-spaces/blob/master/private/validatespaceapi.php

Hey, thank you for helping out, we tried sending them emails before, maybe this time it will work :)

Sorry for having these information more visible, sounds like it could have safed you some time.
If you want to have a list that you can filter you can also use:
```
curl https://api.spaceapi.community/cache
```

its a list with all spaceapi files with the result of the validator. You can also send a link in the email to the validator ui like this:
```
https://validator.spaceapi.io/ui/?url=http://api.service.z-labor.space/spaceapi.json
```
So the spaces can see immediately whats wrong and what they should fix and how to do it.

Thank you for the help and please keep being nice and don't spam them :)

If you want to see your progress you can check:
https://metrics.spaceapi.community/d/vHAszh5mz/spaceapi-directory?orgId=1

**Comment by dbrgn** [comment]
Closing this as stale for now. Comments with updates are still welcome.

**Pull request closed without merging**
