### PR TITLE
Add Hackerspace Szeged

### PR DESCRIPTION
**Pull request by D3vl0per**
Community website: https://www.hackerspace-szeged.org/
Discord server: https://discord.gg/6PeW5dr
Mattermost server: https://chat.hackerspace-szeged.org
Email: info@hackerspace-szeged.org

### CODE REVIEW

**Comment by rnestler** [comment]
Hi @D3vl0per looks good so far :slightly_smiling_face:
One issue: You don't have the CORS headers set correctly (See https://spaceapi.io/getting-started/#common-issues). This means your endpoint won't work with web based apps (such as the https://spaceapi.io/validator/ for example)

**Comment by rnestler** [comment]
Oh another issue: in the API you state the `url` as https://hackerspace-szeged.org/ which gives me a TLS error due to a wrong certificate. https://www.hackerspace-szeged.org/ works fine though.
If I ignore the error it just shows me an empty page with the word "proxy".

**Comment by rnestler** [comment]
Also out of curiosity: I visited a space in szeged in 2017 (http://blog.rnstlr.ch/visiting-hackerspace-szeged.html) is it the same space?

**Comment by D3vl0per** [comment]
Yes. I am the curly hair guy.😀

**Comment by rnestler** [comment]
> Yes. I am the curly hair guy.grinning

Haha. Awesome! I really enjoyed my stay there :slightly_smiling_face:
If you're ever close to https://coredump.ch (probably not in the near future due to CoVID...) drop me a note if you want to visit :slightly_smiling_face:

**Comment by D3vl0per** [comment]
Can you check it again please?

**Comment by D3vl0per** [comment]
Thanks!

**Comment by rnestler** [comment]
> Can you check it again please?

Well the website in `url` is still https://hackerspace-szeged.org/ which is still broken for me.
szeged-ff-error

**Pull request merged**
