### PR TITLE
Update directory.json

### PR DESCRIPTION
**Pull request by dhavlik**
remove terminal21 as it does no longer exist for many years now

### CODE REVIEW

**Comment by dbrgn** [comment]
Hm, endpoint and website are still up though. Blog and feed point to https://eigenbaukombinat.de/, which seems active. Do you know more about the status?

**Comment by dhavlik** [comment]
It doesnt exist as a separate hackspace, it has merged into Eigenbaukombinat 5 years ago. Maybe we can leave this PR Open until someone of the former t21 people give their OK (or not) to remove it since I have not asked them.

**Comment by dbrgn** [comment]
> Maybe we can leave this PR Open until someone of the former t21 people give their OK (or not) to remove it since I have not asked them.

Do you know somebody that we could ping?

**Comment by dbrgn** [comment]
I sent them an e-mail to the address listed in the SpaceAPI endpoint.

**Comment by dbrgn** [comment]
> I sent them an e-mail to the address listed in the SpaceAPI endpoint.

That failed: `Quota exceeded (mailbox for user is full)`

I guess we can merge this PR :slightly_smiling_face: Do you agree @rnestler @gidsi?

**Comment by dbrgn** [comment]
Just got a reply, apparently the e-mail still got through. Terminal 21 *did* merge with Eigenbaukombinat 5 years ago, so this can be merged :slightly_smiling_face: Thanks @dhavlik!

**Pull request merged**
