### PR TITLE
Add "Pomerania Hackerspace"

### PR DESCRIPTION
**Pull request by not7cd**
A. K. A. Hackerspace Pomorze

### CODE REVIEW

**Comment by dbrgn** [comment]
Hey @not7cd, thanks for the update! Note: A comma is missing after the line, otherwise the JSON is not valid.

@gidsi seems we don't validate the JSON yet?

**Comment by gidsi** [comment]
> @gidsi seems we don't validate the JSON yet?

We do this via travis, don't know why it's not working.

**Comment by not7cd** [comment]
@dbrgn, should be good to go

**Review by dbrgn — CHANGES_REQUESTED** [review]
@not7cd sorry for the delay, and thanks for the fix. There's one more issue: CORS headers are not set up properly, this means that your endpoint cannot be used from JavaScript.

https://cors-test.codehappy.dev/?url=https%3A%2F%2Fstatus.hsp.sh%2Fapi%2Fnow&method=get

Adding a `access-control-allow-origin: *` HTTP header in your web server should be sufficient. It would be great if you could fix this!

**Comment by rnestler** [comment]
@not7cd what's the status of this?

@dbrgn I'd be fine with merging it even if CORS headers aren't set up correctly.

**Comment by not7cd** [comment]
@rnestler consider it done, CORS will be fixed.

**Review by dbrgn — APPROVED** [review]
Sorry for the long time without merging, and thanks for the fix!

**Pull request merged**
