### PR TITLE
Add økoyono

### PR DESCRIPTION
**Pull request by f0086**

### CODE REVIEW

**Comment by dbrgn** [comment]
Hi, there are various validation errors in your schema endpoint: https://validator.spaceapi.io/ui/?url=https://spaceapi.okoyono.de/

Could you check and fix those?

**Review by dbrgn — CHANGES_REQUESTED** [review]
https://validator.spaceapi.io/ui/?url=https://spaceapi.okoyono.de/

**Review by rnestler — COMMENTED** [review]
The coordinates seem off as well:

> We found an address to the provided geo coordinates!
> It seems to be in Nepal. Looking good.

Since it looks Germany based you probably want to place it somewhere in Germany, even if it is a "virtual" space.

**Comment by f0086** [comment]
I've fixed the validation issues and add the correct location :)

**Review by rnestler — APPROVED** [review]
Awesome! Thanks :slightly_smiling_face:

**Pull request merged**
