### PR TITLE
Add Makerspace Leiden / https://makerspaceleiden.nl

### PR DESCRIPTION
**Pull request by dirkx**

### CODE REVIEW

**Comment by dbrgn** [comment]
Thanks! Could you maybe set content-type and CORS HTTP headers on your response?

https://validator.spaceapi.io/ui/?url=https://makerspaceleiden.nl/crm/spaceapi/0.13

**Comment by rnestler** [comment]
@dirkx Bump.

**Comment by dbrgn** [comment]
Additionally, the JSON is currently malformed:

```json
  "lastchange": ,
```

The `lastchange` key doesn't have a value.

**Comment by rnestler** [comment]
> https://validator.spaceapi.io/ui/?url=https://makerspaceleiden.nl/crm/spaceapi/0.13

The validator gives me a 500 error. Any reason for that? @gidsi maybe?

**Comment by dbrgn** [comment]
> > https://validator.spaceapi.io/ui/?url=https://makerspaceleiden.nl/crm/spaceapi/0.13
> 
> The validator gives me a 500 error. Any reason for that? @gidsi maybe?

See my comment above, the reason was that it can't even parse the JSON 🙂 There's probably some error handling missing. It works again now.

**Comment by rnestler** [comment]
>      See my comment above, the reason was that it can't even parse the JSON slightly_smiling_face There's probably some error handling missing. It works again now.

Yes, sounds like it. Failing to parse the JSON should still return the error to the user and not fail internally :slightly_smiling_face:

**Comment by dirkx** [comment]
On the source side - CORS Headers have been added to make the validator happier. All 'green's now.

**Comment by dirkx** [comment]
> Thanks! Could you maybe set content-type and CORS HTTP headers on your response?
> 
> https://validator.spaceapi.io/ui/?url=https://makerspaceleiden.nl/crm/spaceapi/0.13

Done

**Comment by dirkx** [comment]
> Additionally, the JSON is currently malformed:
> 
> ```json
>   "lastchange": ,
> ```
> 
> The `lastchange` key doesn't have a value.

I have serious trouble replicating this bug. As we set a `lst = datetime.datetime(1970, 1, 1)` default right at he top. It appears if you do a ` https://makerspaceleiden.nl/crm/spaceapi/0.13` too ?

**Comment by rnestler** [comment]
Nice. Thanks @dirkx for the effort! You could consider adding v14 support as well (it's possible to be compatible with both versions at the same time, see https://spaceapi.io/ for an example)

**Review by rnestler — APPROVED** [review]

**Comment by dirkx** [comment]
On 22 Aug 2022, at 13:38, Raphael Nestler ***@***.***> wrote:
> Nice. Thanks @dirkx <https://github.com/dirkx> for the effort! You could consider adding v14 support as well (it's possible to be compatible with both versions at the same time, see https://spaceapi.io/ <https://spaceapi.io/> for an example)

Done.

**Pull request merged**
