### PR TITLE
Update directory.json

### PR DESCRIPTION
**Pull request by Pixtxa**
fixed toolbox bodensee to their new url

### CODE REVIEW

**Comment by dbrgn** [comment]
Thanks! It seems that CORS is not enabled on your server, meaning that JavaScript applications cannot query your endpoint. Usually just adding a `access-control-allow-origin: *` header to the webserver should be sufficient.

@gidsi shouldn't the url check flag runs without CORS as failed?

**Comment by gidsi** [comment]
> @gidsi shouldn't the url checker mark urls without CORS as failed?

So far we agreed on CORS being highly appreciated but we would still merge if they are not available ([e.g.](https://github.com/SpaceApi/directory/pull/116#pullrequestreview-319881713)).

If we would let the check fail the pullrequest would be unmergable.

**Comment by dbrgn** [comment]
Can the bot post a comment explaining what CORS is and why it's desireable to have?

**Comment by gidsi** [comment]
> Could the bot post a comment explaining what CORS is and why it's desireable to have?

Yes. that's the next step on the bot. So far we've just implemented a short overview to check everything we had to check manually, next step is to bring it to human readable form.

**Comment by Pixtxa** [comment]
Well, I'm not from toolbox, just wanted to visit them but I've seen there are no stats avialabe about that space, but they've an opening status on their webside. Found out they've changed their path on their server without changing it here. I didn't notice that it may didn't work for all clients, so maybe it's better to let it be broken so they can fix it by themselves?

**Comment by gidsi** [comment]
> Well, I'm not from toolbox, just wanted to visit them but I've seen there are no stats avialabe about that space, but they've an opening status on their webside. Found out they've changed their path on their server without changing it here. I didn't notice that it may didn't work for all clients, so maybe it's better to let it be broken so they can fix it by themselves?

I'm sorry, of course we'll merge it, thanks for your help :)

**Pull request merged**
