### PR TITLE
Update directory.json

### PR DESCRIPTION
**Pull request by justM4D**
add ibbspace

### CODE REVIEW

**Comment by s3lph** [comment]
Hi @justM4D, thanks for your contribution!

Please make sure your endpoint conforms to the API specification. You can use the validator at https://validator.spaceapi.io/ui/ to check your endpoint for errors. At the moment it's reporting 3 errors:

- "issue-mail" is a nonstandard contact field which can't be used in the `issue_reports_channel`.
- `state.open` should be a boolean, `state.lastchange` should be an integer, however both are strings in your endpoint.

In addition, it seems that CORS is not enabled on your new endpoint, meaning that it can't be queried by JavaScript browser apps. Usually just adding an `Access-Control-Allow-Origin: *` header to the webserver should be sufficient. Would it be possible to set up CORS on your end?

Finally, though not required at this point, you may also want to consider adopting the latest API version, 14. This would also resolve the "issue-mail" problem since the `issue_reports_channel` was removed in v14. However, there are most likely still some clients which only support 0.13, so at least for the time being you may want to be compliant to both versions. You can check e.g. https://spaceapi.io/ for an example that conforms to both versions simultaneously. You can find the v14 documentation here: https://spaceapi.io/docs/

**Comment by justM4D** [comment]
Hi @s3lph,
thanks for the quick reply. I made the necessary changes.
I wasn't aware of spaceapi.io and their v14, I only knew about spaceapi.net, since that was referenced by other *spaces I checked out.

The `issue-mail` vs. `issue_mail` thing was my bad, I guess I didn't read that properly and had no validator to check against on spaceapi.net.

**Comment by rnestler** [comment]
> I wasn't aware of spaceapi.io and their v14, I only knew about spaceapi.net, since that was referenced by other *spaces I checked out.

Where was spaceapi.net referenced? It would be nice if they could update it to spaceapi.io

**Comment by rohieb** [comment]
@rnestler Thanks for the hint, fixed.

**Pull request merged**
