### PR TITLE
Modified entry for DingFabrik e.V., Cologne

### PR DESCRIPTION
**Pull request by duese**

### CODE REVIEW

**Comment by rnestler** [comment]
Since the old link doesn't work and the new one does I think this is good to merge :)

**Comment by rnestler** [comment]
The issue mail looks a bit odd, though: `issue_mail: "cG9zdEBkaW5nZmFicmlrLmRl"`

**Comment by duese** [comment]
Changed to https.

**Comment by rnestler** [comment]
@dbrgn Do you approve as well?

**Comment by rnestler** [comment]
> @dbrgn Do you approve as well?

Ping @dbrgn.

**Pull request merged**
