### PR TITLE
Update address for CCC Darmstadt

### PR DESCRIPTION
**Pull request by fleaz**

### CODE REVIEW

**Comment by fleaz** [comment]
This is currently a draft because we use HomeAssistant as a backend to generate the SpaceAPI json and due to a bug some values are strings instead of numbers. See https://validator.spaceapi.io/ui/?url=https://api.chaos-darmstadt.de for more infos

**Comment by mweinelt** [comment]
Patched and should be fine, but the validator seems to error out, because it chokes on the compression.

**Comment by fleaz** [comment]
Validator is green and compression problems has been fixed :)

**Comment by dbrgn** [comment]
@gidsi the validator is having an issue with this URL:

```
danilo@c3po:~$ http POST https://validator.spaceapi.io/v2/validateURL url=https://api.chaos-darmstadt.de
HTTP/1.1 500 Internal Server Error
Content-Length: 53
Content-Type: text/plain; charset=utf-8
Date: Sat, 07 Jan 2023 23:50:04 GMT
Vary: Origin
X-Content-Type-Options: nosniff

invalid character 'x' looking for beginning of value
```

Any idea? The content looks valid at first glance, there's no stray "x" in the JSON.

**Comment by dbrgn** [comment]
In any case, when posting the JSON directly to the validator, it validates successfully 🙂 Thanks for the update!

**Review by dbrgn — APPROVED** [review]

**Comment by mweinelt** [comment]
The compressed response starts with an x, so I wonder whether the validator handles compression correctly.

**Comment by dbrgn** [comment]
@mweinelt good hint, I copied your comment to https://github.com/SpaceApi/validator/issues/63

**Pull request merged**
