### PR TITLE
Add hacKNology e.V. to directory

### PR DESCRIPTION
**Pull request by xperimental**
This adds "hacKNology e.V." to the directory. It is a hackerspace in Konstanz, Germany.

### CODE REVIEW

**Review by rnestler — APPROVED** [review]
Looks good to me and validator approves: https://validator.spaceapi.io/ui/?url=https://www.hacknology.de/spaceapi/status.json

You could consider adding v14 support. See https://spaceapi.io/ for an example that is both v0.13 and v14 compatible.

**Comment by xperimental** [comment]
Sorry for the slow reply. I planned to look into updating our API to v14 yesterday but did not get to it yet.

I already had a look at a diff of the two schemas and if I'm not missing anything, then I think the thing missing is the attribute announcing the compatibility and some new attributes about new social network services (the only relevant one I've seen is Mastodon).

Is the change to v14 required for getting this PR merged?

**Comment by rnestler** [comment]
> I already had a look at a diff of the two schemas and if I'm not missing anything, then I think the thing missing is the attribute announcing the compatibility

I think just adding `"api_compatibility": ["14"],` should be enough in your case.

> Is the change to v14 required for getting this PR merged?

No, I can merge it now.

**Comment by xperimental** [comment]
@rnestler Thanks!

**Pull request merged**
