### PR TITLE
Added the Computer Deconstruction Lab

### PR DESCRIPTION
**Pull request by compdecon**
Added Computer Deconstruction Laboratory (CDL) - The Jersey Shore Makerspace

### CODE REVIEW

**Comment by compdecon** [comment]
I understand that a check failed but when I check https://compdecon.github.io/status.json  in my browser I get the actual JSON. Not sure why the check gets a 404.

**Comment by gidsi** [comment]
Hey, sorry, the result is a bit misleading, here is a proper readable validation result:
https://validator.spaceapi.io/ui/?url=https://compdecon.github.io/status.json

In detail:
```
(root).cam: Array must have at least 1 items
(root).events.1: name is required
(root).events.1: type is required
(root).events.1: timestamp is required
(root).location: lon is required
(root).sensors.temperature.0.unit: sensors.temperature.0.unit must be one of the following: \"°C\", \"°F\", \"K\", \"°De\", \"°N\", \"°R\", \"°Ré\", \"°Rø\"
(root).sensors.temperature.1.unit: sensors.temperature.1.unit must be one of the following: \"°C\", \"°F\", \"K\", \"°De\", \"°N\", \"°R\", \"°Ré\", \"°Rø\"
(root).sensors.temperature.2.unit: sensors.temperature.2.unit must be one of the following: \"°C\", \"°F\", \"K\", \"°De\", \"°N\", \"°R\", \"°Ré\", \"°Rø\"
(root).sensors.temperature.3.unit: sensors.temperature.3.unit must be one of the following: \"°C\", \"°F\", \"K\", \"°De\", \"°N\", \"°R\", \"°Ré\", \"°Rø\"
```

If we can help you somehow please let us know :)

**Comment by rnestler** [comment]
Also the temperatures look strange:
```
      {
        "location": "Lab",
        "unit": "°K",
        "value": 70
      },
```

So the unit `°K` doesn't exist. If it is in Kelvin, the unit should be just `K`. Also 70K is around -200°C which probably is wrong. It looks more like a Fahrenheit temperature, so the unit should be `°F`.

**Comment by compdecon** [comment]
I did find the validator (a bit later) and I've corrected the mistakes. My status.json now validates proprerly. Sorry about that.

**Comment by gidsi** [comment]
No problem :)

You can leave this pull request open, no need to open another one :)

**Comment by compdecon** [comment]
Ah, so my directions were not so good ... definitely not in Antarctica! I've corrected the LAT and LON. Validator says we're in the USA. ;-)

**Review by gidsi — APPROVED** [review]
LGTM

**Pull request merged**
