### PR TITLE
Updated with kwartzlab

### PR DESCRIPTION
**Pull request by moridin1138**
Added kwartzlab makerspace from Kitchener, Ontario, Canada

### CODE REVIEW

**Comment by s3lph** [comment]
@moridin1138 thanks for your contribution!

However, please have a look at the JSON data served by your endpoint: Starting with SpaceAPI schema version 14, the version isn't encoded in the `.api` field anymore, but in the `api_compatibility` array, e.g.:
```json
{
  "api_compatibility": [
    "14",
  ],
  ...
}
```
Afterwards, please make sure your endpoint adheres to the rest of the specification by using the validator at https://validator.spaceapi.io/ui/

**Comment by moridin1138** [comment]
Hi Sebastian,

Thanks for the heads up.  I would love to use the validator, but it doesnt
appear to be working for either URL's or the direct copy.  I've tried it on
multiple browsers and computers, but clicking validate doesnt appear to do
anything.  Is it broken?

Thanks,

-brian

**Comment by moridin1138** [comment]
@s3lph Validator is working again.  Updated and validated the json.  Appears to be ok.

**Review by dbrgn — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
