### PR TITLE
Add Fuz hackerspace

### PR DESCRIPTION
**Pull request by Lomanic**
The Fuz is a hackerspace in Paris, see also https://wiki.hackerspaces.org/FUZ

Thanks for the useful service you provide!

### CODE REVIEW

**Comment by gidsi** [comment]
Hey your endpoint seems to have a problem, i get the following:
```
err: bad json from presence API: invalid character '<' looking for beginning of value
```

**Comment by rnestler** [comment]
It seems to work now. Did you change anything on your side @Lomanic? Can we trigger the Url check again @gidsi?

**Comment by Lomanic** [comment]
@rnestler the current code is fragile, I only relaunched the crashed web service (presence.fuz.re) from where spaceapi.fuz.re gets some of its data (opened/closed status and last update timestamp). I will improve reliability both in the spaceapi and presence (still didn't have time).

**Review by gidsi — APPROVED** [review]

**Comment by gidsi** [comment]
> It seems to work now. Did you change anything on your side @Lomanic? Can we trigger the Url check again @gidsi?

@rnestler You can add the recheck label to trigger one :)

**Pull request merged**
