### PR TITLE
IT-Syndikat: spaceapi has moved to its own subdomain

### PR DESCRIPTION
**Pull request by Xiretza**

### CODE REVIEW

**Comment by dbrgn** [comment]
@Xiretza thanks for the update! Since we're at it: The current endpoint is not valid according to the schema, the `issue_report_channels` key is missing. Could you fix that?

**Comment by Xiretza** [comment]
Ah, we had upgraded the API to v14-only, but then had to add back v13 compatibility for some clients, and forgot to restore that key. Thanks!

**Review by rnestler — APPROVED** [review]
Thanks looks good according to https://validator.spaceapi.io/ui/, but the logo, and open/closed URLs return a 404 for me.

**Comment by Xiretza** [comment]
My bad, I had them in my browser cache, so I didn't notice they'd broken. Fixed now.

**Review by dbrgn — APPROVED** [review]

**Pull request merged**
