### PR TITLE
Add "Schülerforschungszentrum der Hochschule Aalen" / https://api.sfz-aalen.space/spaceapi.json

### PR DESCRIPTION
**Pull request by lucalutz2005-dev**
Add Schülerforschungszentrum der Hochschule Aalen

### CODE REVIEW

**Review by dbrgn — APPROVED** [review]
Even with v13/v14 compatibility, nice!

**Comment by Steamrunner** [comment]
this commit doesn't follow the json standard... please revert and fix

**Comment by gidsi** [comment]
> this commit doesn't follow the json standard... please revert and fix

Fixed in #198 , thank you!

**Comment by lucalutz2005-dev** [comment]
Sorry this was my mistake, thank you for resolving it 👍

**Pull request merged**
